### ISSUE TITLE
Errors during compilation

### ISSUE THREAD

**Issue by DeVrtl** [adamhlt/D3D11-Overlay-ImGui#1]
I had these problems when compiling. I have DXSDK_DIR declared in environment variables and the latest version of DirectX installed. I also set the path to DirectX in Properties in VC++ Directories in Include Directories
![CompileErrors](https://github.com/adamhlt/D3D11-Overlay-ImGui/assets/88022703/231acfdb-66a3-44f5-bc06-60189e364194)

**Comment by adamhlt** [comment]
Hi, did you make some modification to the code ? Can you provide me more details ?

**Comment by DeVrtl** [comment]
I haven't touched anything in the code. I just downloaded the repository and set the path to DirectX in Properties in VC++ Directories in Include Directories. Without setting the path it doesn't work either

**Comment by adamhlt** [comment]
I have tested build on 2 different computer as DLL and EXE and everything works fine. It seems that this is not related to DirectX. I don't understand why you have function redefinition error since these functions are only define once.

**Comment by DeVrtl** [comment]
Well I'll go test it on another pc too then.

**Comment by adamhlt** [comment]
> I haven't touched anything in the code. I just downloaded the repository and set the path to DirectX in Properties in VC++ Directories in Include Directories. Without setting the path it doesn't work either

The path of DirectX is not related to my project, the path is set when you install DirectX SDK. So, everybody that have DirectX SDK installed can't have an issue with the project configuration.

**Comment by DeVrtl** [comment]
I tried it on another computer and there I had to install Visual Studio from scratch with two components "Desktop development with C++" and "Game development with C++" and everything compiles there. I also checked the dll I compiled on the second PC and it works. Most likely there are some unnecessary modules on the main computer because of which it doesn't compile.
