### ISSUE TITLE
Desktop window manager (DWM) high gpu usage!

### ISSUE THREAD

**Issue by exp1007** [adamhlt/D3D11-Overlay-ImGui#3]
Hello, there is a problem with DWM when using LWA_ALPHA, this flag will decrease the performance a lot. In my case it uses 20-30% GPU and that's a lot.
I also have my own project based on directx11 for an external overlay and after I optimized most of my program I realized there are low usage % but still unstable fps and sent me to this process that's eating my GPU after running the overlay.
I couldn't find a fix for this but people suggested making the back buffer transparent since your window is already transparent from the flag WS_EX_TRANSPARENT in CreateWindowExW.
I saw your other repository called Imgui-Standalone and after a quick run it doesn't affect DWM's performance that much, a choppy fix would be to create the window as fullscreen and just limit the "ImGui::Begin" to targeted client's window dimensions. I didn't have the time to go through your both project's code, I just realized you got the same method for making the window transparent as me. I am sorry for this, I will go through it in-depth tomorrow and come with edits/news if any.

**Comment by adamhlt** [comment]
Thanks for reporting this, I see the problem, if I have time I'll try to fix it.

**Comment by swisscheez2** [comment]
I'm not wrong in assuming this was never solved right? Or did I miss something.

**Comment by adamhlt** [comment]
Hello, no I didn't try to benchmark the program to check the GPU usage. Feel free to create a pull request if you have a fix.
