### ISSUE TITLE
how to fix that it doesn't draw the bottom part in the MSTaskListWClass

### ISSUE THREAD

**Issue by DevDevoe** [adamhlt/D3D11-Overlay-ImGui#4]
![image](https://github.com/adamhlt/D3D11-Overlay-ImGui/assets/145042376/97a2a029-b00c-4362-b91e-dbc4f9b8e9a6)
it does not draw the full screenHeight .
it does not draw the bottom part in the MSTaskListWClass

**Comment by adamhlt** [comment]
Thank's for reporting the bug, can you provide more details about the problem. I will try to fix it when I have free time.

**Comment by DevDevoe** [comment]
@adamhlt https://streamable.com/t9anzw

**Comment by DevDevoe** [comment]
found the solution .

    //lWindowWidth -= 5;
    //lWindowHeight -= 29;

**Comment by DevDevoe** [comment]
//lWindowWidth -= 5;
    //lWindowHeight -= 29;
