### ISSUE TITLE
cannot open file 'Lib\x64\d3d11.lib'

### ISSUE THREAD

**Issue by scemmaz** [adamhlt/D3D11-Overlay-ImGui#5]
While building the project im keep getting this error.

![image](https://github.com/adamhlt/D3D11-Overlay-ImGui/assets/120191423/7d38845c-ad39-4ac8-a47a-00be23ca97cb)

**Comment by adamhlt** [comment]
Just read the [README](https://github.com/adamhlt/D3D11-Overlay-ImGui#rocket-getting-started), I'll close the issue.
