### ISSUE TITLE
About a doubt (maybe a bug)

### ISSUE THREAD

**Issue by zhongmof** [adamhlt/D3D11-Overlay-ImGui#7]
Why is there one less thing on the left side of my menu?
![image](https://github.com/user-attachments/assets/41248e52-a318-424e-a0f1-1fabcf254253)
I've set the coordinates to (0,0) and I've even tried setting it to a negative number, but it doesn't work, I hope you can get back to me when you see it, thank you very much

**Comment by exp1007** [comment]
That's the window padding, it's all related to how imgui works. You can change `ImGuiStyleVar_WindowPadding` using `ImGui::PushStyleVar()` function. You can check out the demo from imgui, there's enough info there to help you find out how everything works.

**Comment by adamhlt** [comment]
@exp1007 thanks for the answer, you give all the information. I really appreciate.
@zhongmof I'll close the issue since it's not related to my project. You can find all the information in the ImGui's documentation.

**Comment by zhongmof** [comment]
Okay, thank you very much that I was careless
