### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by zhongmof** [adamhlt/D3D11-Overlay-ImGui#8]
I encountered a strange problem where the bottom part of the GUI window was not displayed, while the left and top parts were protruding.   I think the display of the bottom part is an error because the window title was mistakenly treated as the content of the window itself.   I think it's a bug and I hope it can be fixed.   Thank you.

https://github.com/user-attachments/assets/8faea31a-92c2-47f6-bb82-be5623db6e1a

**Comment by adamhlt** [comment]
This is the second time you open an issue that is not related to my project. As it was said before, you have to learn how to use ImGui. Your problem have been already treated in the ImGui's issues.

Next time I will mark the issue as resolved without any answers.

**Comment by zhongmof** [comment]
Could you take a look at the video? I don't think this is a problem with imgui per se

**Comment by adamhlt** [comment]
I'm categorical, there's no bug. The overlay window can't adapt to all existing window shapes, it's up to you to change the position and size values of the overlay so that it fits perfectly. But I thought you were smart enough to at least open the code and modify the `MoveWindow` function.  This is your job not mine.

```c
/**
    @brief : Function that move the overlay on top of the targeted window.
    @param hCurrentProcessWindow : Window of the overlay.
**/
void UI::MoveWindow(const HWND hCurrentProcessWindow)
{
    RECT rect;
    if (hTargetWindow == nullptr)
        return;

    GetWindowRect(hTargetWindow, &rect);

    int lWindowWidth = rect.right - rect.left;
    int lWindowHeight = rect.bottom - rect.top;

    lWindowWidth -= 10;
    lWindowHeight -= 6;

    SetWindowPos(hCurrentProcessWindow, nullptr, rect.left+5, rect.top, lWindowWidth, lWindowHeight, SWP_SHOWWINDOW);
}
```

**Comment by zhongmof** [comment]
Okay, I'm sorry I'm new to this and I thought this was an easy problem to handle and I'm sorry to bother you
