### ISSUE TITLE
Black Background?

### ISSUE THREAD

**Issue by samjviana** [adamhlt/D3D11-Overlay-ImGui#9]
I just downloaded/compiled your project, got everything compiled without errors. I'm now trying to inject the .dll into the game (just like the demo video). The overlay appears, but it has this black background convering almost the whole game screen.
Is this something on the game's side? Or can it be related to the overlay itself?

![Vdeo-sem-ttulo-Feito-com-o-Clipc](https://github.com/user-attachments/assets/716beeb5-75b7-4ac9-832b-f894b6c67014)

**Comment by 90th** [comment]
The dll is meant for injecting into another process.

**Comment by adamhlt** [comment]
It seems the window overlay do not render properly. I was not able to reproduce the bug, but you can try to change the parameter of the window overlay and see if something change.

**Comment by adamhlt** [comment]
@samjviana I closed the issue, feel free to open it again with new information.
